### ISSUE TITLE
[Fix] 블럭 구동 오류 고치기

### ISSUE THREAD

**Issue by ParkSoonHong** [Mtvs-FinalProject/-Unreal#6]
### ISSUE

- Type: Fix
- Detail: 블럭 조합에 여러 오류 고치기

### TODO

- [x]  순서대로는 분리 가능하게 만들기
- [x]  중간 분리 불가능 해결
- [x] 스냅 위치에 붙이는것 불가능 해결
- [x]  자식 검사해서 붙이기 불가능 해결
